### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.5 voor Windows-desktops
  description: Microsoft Application Virtualization Hosting 4.5 voor Windows Desktops volgt het vaste levenscyclusbeleid.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 2e50dff8c1e7f1db82d46a06704bad1c76d16598
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4154029"
name: Microsoft Application Virtualization Hosting 4.5 voor Windows-desktops
summary: >
  Microsoft Application Virtualization Hosting 4.5 voor Windows Desktops volgt het [vaste](/lifecycle/policies/fixed) levenscyclusbeleid.


  Dit geldt voor de volgende edities: voor Windows Desktops


  > [!IMPORTANT]

  > De ondersteuning voor dit product is beëindigd. Zie onderstaande migratiegegevens.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Koppelingen \n* [Product- en migratiegegevens](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Servicepackbeleid](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edities \n* voor Windows Desktops"
