### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: Microsoft System Center Configuration Manager 2007 R3 volgt het vaste levenscyclusbeleid.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  Microsoft System Center Configuration Manager 2007 R3 volgt het [vaste](/lifecycle/policies/fixed) levenscyclusbeleid.


  > [!IMPORTANT]
  > De ondersteuning voor dit product is beëindigd. Zie hieronder de richtlijnen voor migratie.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Koppelingen 
  * [Richtlijnen voor migratie](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Aanvullende migratierichtlijnen](/mem/configmgr/core/migration/planning-for-migration)