### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: Microsoft Application Virtualization 4.6 volgt het vaste levenscyclusbeleid.
  ms.date: 09/01/2020
  keywords: 'for Remote Desktop Services,for Windows Desktops,Sequencer'
name: Microsoft Application Virtualization 4.6
summary: |+
  Microsoft Application Virtualization 4.6 volgt het [vaste](/lifecycle/policies/fixed) levenscyclusbeleid.

  Dit geldt voor de volgende edities: voor Extern bureaublad-services, voor Windows-desktops, Sequencer

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Koppelingen 
  * [Product- en migratiegegevens](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Richtlijnen voor migratie](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)
  * [Servicepackbeleid](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Aangezien App-V 4.6-client gebruikmaakt van de App-V 4.5-server, wordt de App-V 4.5-server verder ondersteund op basis van de datums van de levenscyclus van App-V 4.6 wanneer deze wordt gebruikt met de ondersteunde App-V 4.6-client.

  ## <a name="editions"></a>Edities 
  * Voor Extern bureaublad-services
  * voor Windows Desktops
  * Sequencer