### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.5
  description: Microsoft Application Virtualization 4.5 volgt het vaste levenscyclusbeleid.
  ms.date: 09/01/2020
  keywords: for Terminal Services,for Windows Desktops
  ms.openlocfilehash: d70bed6b9c9e05d19efb27509f15e13fb8bf5735
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: nl-NL
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4108297"
name: Microsoft Application Virtualization 4.5
summary: >
  Microsoft Application Virtualization 4.5 volgt het [vaste](/lifecycle/policies/fixed) levenscyclusbeleid.


  Dit geldt voor de volgende edities: voor Terminal Services, voor Windows Desktops


  > [!IMPORTANT]

  > De ondersteuning voor dit product is beëindigd. Zie hieronder de richtlijnen voor migratie.
products:
- windows
policyType: fixed
supportDates:
  start: 2008-11-23T00:00:00.000-08:00
  end: 2014-01-14T22:59:59.999-08:00
  extendedEnd: 2019-01-08T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2010-08-15T00:00:00.000-08:00
  endDate: 2019-01-08T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2009-12-13T00:00:00.000-08:00
  endDate: 2011-10-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2008-11-23T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Koppelingen \n* [Richtlijnen voor migratie](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Servicepackbeleid](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Aangezien App-V 4.6-client gebruikmaakt van de App-V 4.5-server, wordt de App-V 4.5-server verder ondersteund op basis van de datums van de levenscyclus van App-V 4.6 wanneer deze wordt gebruikt met de ondersteunde App-V 4.6-client.\n\n## <a name=\"editions\"></a>Edities \n* voor Terminal Services\n* voor Windows Desktops"
